[package]
name = "bmuisc"
version = "0.1.0"
description = "B 站音乐播放器"
authors = ["roy2651"]
edition = "2021"

[lib]
name = "bmuisc_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "stream"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
axum = { version = "0.8", features = ["http1"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
